#!/bin/bash
# =====================================================
#  VAM OS Build Environment Setup (Arch Linux)
# =====================================================

set -e

sudo pacman -Syu --needed \
    base-devel \
    gcc-multilib \
    nasm \
    qemu-full \
    grub \
    xorriso \
    mtools \
    make \
    git

echo "✅ Build environment ready!"
